apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-controller
spec:
  rules:
    - host: edirect.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: auth-srv
              servicePort: 80